### ISSUE TITLE
How can an API key be added?

### ISSUE THREAD

**Issue by zoechi** [GoogleWebComponents/google-url-shortener#7]
I always get 

> Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.

**Comment by ebidel** [comment]
You can do:
```
shortenerEl.addEventListener('google-api-load', e = > {
   gapi.client.setApiKey(apiKey);
});
``` 

We should make this easier though. There should be an `apiKey` property just like the maps element:
https://github.com/GoogleWebComponents/google-map/blob/master/google-map.html#L147
